---
  -hosts: myhosts
   gather_facts: yes
   tasks:
     - name: ping the hosts


       tasks:
  - name: Check if commvault is already installed
    shell: commvault status
    register: commvault_is_installed
    failed_when: no



    ---

state = present, latest, absent
Present = installer denne
absent = fjern denne


- hosts: group1
  tasks:
  - name: Enable SELinux
    selinux:
      state: enabled
    when: ansible_os_family == 'Debian'
    register: enable_selinux

  - debug:
      msg: "Selinux Enabled. Please restart the server to apply changes."
    when: enable_selinux.changed == true

- hosts: group2
  tasks:
  - name: Install apache
    yum:
      name: httpd
      state: present
    when: ansible_system_vendor == 'HP' and ansible_os_family == 'RedHat'
